common:
  dev_mode: true
  return_exceptions: false

ipc:
  secret_key: <RANDOM SECRET KEY>

db:
  host: <DATABASE HOST>
  name: <DATABASE NAME>
  user: <DATABASE USER>
  password: <DATABASE PASSWORD>
  use_dns_seed_list: true
  retry_writes: true
  write_concern: majority

bot:
  token: <BOT TOKEN>
  dev_server_id: <ID OF DEV SERVER>
  owner_id: <ID OF BOT OWNER>

api:
  enabled: true

oauth:
  client_id: <CLIENT ID>
  client_secret: <CLIENT SECRET>
  redirect_uri: <REDIRECT URI>
  scopes:
    - identify
    - email
    - guilds